package output

import (
	"bytes"
	"fmt"
	"net/netip"
	"strings"

	"github.com/isnogudus/zonefile-go/internal/zone"
)

// Dhcpd returns a complete dhcpd.conf(5) for OpenBSD dhcpd: the global
// settings, if any, then one subnet declaration per dhcp block with a host
// declaration per MAC address.
func Dhcpd(global *zone.DHCPGlobal, subnets []*zone.Subnet) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by zonefile-go; do not edit.\n")
	if global != nil {
		b.WriteByte('\n')
		dhcpdServer(&b, "", global.ServerID, global.Authoritative)
		dhcpdOptions(&b, "", global.DHCPOptions)
	}
	for _, s := range subnets {
		b.WriteByte('\n')
		dhcpdSubnet(&b, s)
	}
	return b.Bytes()
}

// netmask returns the netmask of an IPv4 prefix, e.g. 255.255.255.0.
func netmask(p netip.Prefix) netip.Addr {
	var m [4]byte
	for i := 0; i < p.Bits(); i++ {
		m[i/8] |= 0x80 >> (i % 8)
	}
	return netip.AddrFrom4(m)
}

func addrs(list []netip.Addr) string {
	s := make([]string, len(list))
	for i, a := range list {
		s[i] = a.String()
	}
	return strings.Join(s, ", ")
}

func quoted(list []string) string {
	s := make([]string, len(list))
	for i, v := range list {
		s[i] = `"` + v + `"`
	}
	return strings.Join(s, ", ")
}

// dhcpdOptions writes the options of a subnet or profile, each line
// indented by indent.
func dhcpdOptions(b *bytes.Buffer, indent string, o zone.DHCPOptions) {
	if len(o.Routers) > 0 {
		fmt.Fprintf(b, "%soption routers %s;\n", indent, addrs(o.Routers))
	}
	if len(o.DNSServers) > 0 {
		fmt.Fprintf(b, "%soption domain-name-servers %s;\n", indent, addrs(o.DNSServers))
	}
	if o.Domain != "" {
		fmt.Fprintf(b, "%soption domain-name %q;\n", indent, o.Domain)
	}
	if len(o.Search) > 0 {
		fmt.Fprintf(b, "%soption domain-search %s;\n", indent, quoted(o.Search))
	}
	if len(o.NTPServers) > 0 {
		fmt.Fprintf(b, "%soption ntp-servers %s;\n", indent, addrs(o.NTPServers))
	}
	if len(o.SMTPServers) > 0 {
		fmt.Fprintf(b, "%soption smtp-server %s;\n", indent, addrs(o.SMTPServers))
	}
	if o.AutoproxyScript != "" {
		fmt.Fprintf(b, "%soption autoproxy-script %q;\n", indent, o.AutoproxyScript)
	}
	if o.GetLeaseHostnames != nil {
		fmt.Fprintf(b, "%sget-lease-hostnames %t;\n", indent, *o.GetLeaseHostnames)
	}
	if o.Lease != 0 {
		fmt.Fprintf(b, "%sdefault-lease-time %d;\n", indent, o.Lease)
	}
	if o.MaxLease != 0 {
		fmt.Fprintf(b, "%smax-lease-time %d;\n", indent, o.MaxLease)
	}
}

func dhcpdHosts(b *bytes.Buffer, indent string, hosts []zone.DHCPHost) {
	for _, h := range hosts {
		fmt.Fprintf(b, "\n%shost %s {\n", indent, h.Name)
		fmt.Fprintf(b, "%s\thardware ethernet %s;\n", indent, h.MAC)
		fmt.Fprintf(b, "%s\tfixed-address %s;\n", indent, addrs(h.Addrs))
		fmt.Fprintf(b, "%s\toption host-name %q;\n", indent, h.HostName)
		fmt.Fprintf(b, "%s}\n", indent)
	}
}

func dhcpdSubnet(b *bytes.Buffer, s *zone.Subnet) {
	fmt.Fprintf(b, "subnet %s netmask %s {\n", s.Network.Addr(), netmask(s.Network))
	dhcpdServer(b, "\t", s.ServerID, s.Authoritative)
	dhcpdOptions(b, "\t", s.Write)
	for _, r := range s.Ranges {
		fmt.Fprintf(b, "\trange %s %s;\n", r.Low, r.High)
	}
	dhcpdHosts(b, "\t", s.Hosts)
	// A profile becomes a group, whose options override those of the
	// subnet for its hosts. Profiles without hosts are left out.
	for _, p := range s.Profiles {
		if len(p.Hosts) == 0 {
			continue
		}
		fmt.Fprintf(b, "\n\t# dhcp-profile %s\n\tgroup {\n", p.Name)
		dhcpdOptions(b, "\t\t", p.DHCPOptions)
		dhcpdHosts(b, "\t\t", p.Hosts)
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
}

func dhcpdServer(b *bytes.Buffer, indent string, id netip.Addr, authoritative *bool) {
	if id.IsValid() {
		fmt.Fprintf(b, "%sserver-identifier %s;\n", indent, id)
	}
	if authoritative != nil {
		if *authoritative {
			fmt.Fprintf(b, "%sauthoritative;\n", indent)
		} else {
			fmt.Fprintf(b, "%snot authoritative;\n", indent)
		}
	}
}
