package output

import (
	"bytes"
	"fmt"
	"net/netip"
	"strings"

	"github.com/isnogudus/zonefile-go/internal/zone"
)

// Dhcpd returns a complete dhcpd.conf(5) for OpenBSD dhcpd with one subnet
// declaration per dhcp block and a host declaration per MAC address.
func Dhcpd(subnets []*zone.Subnet) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by zonefile-go; do not edit.\n")
	for _, s := range subnets {
		b.WriteByte('\n')
		dhcpdSubnet(&b, s)
	}
	return b.Bytes()
}

// netmask returns the netmask of an IPv4 prefix, e.g. 255.255.255.0.
func netmask(p netip.Prefix) netip.Addr {
	var m [4]byte
	for i := 0; i < p.Bits(); i++ {
		m[i/8] |= 0x80 >> (i % 8)
	}
	return netip.AddrFrom4(m)
}

func addrs(list []netip.Addr) string {
	s := make([]string, len(list))
	for i, a := range list {
		s[i] = a.String()
	}
	return strings.Join(s, ", ")
}

func quoted(list []string) string {
	s := make([]string, len(list))
	for i, v := range list {
		s[i] = `"` + v + `"`
	}
	return strings.Join(s, ", ")
}

func dhcpdSubnet(b *bytes.Buffer, s *zone.Subnet) {
	fmt.Fprintf(b, "subnet %s netmask %s {\n", s.Network.Addr(), netmask(s.Network))
	if len(s.Routers) > 0 {
		fmt.Fprintf(b, "\toption routers %s;\n", addrs(s.Routers))
	}
	if len(s.DNSServers) > 0 {
		fmt.Fprintf(b, "\toption domain-name-servers %s;\n", addrs(s.DNSServers))
	}
	if s.Domain != "" {
		fmt.Fprintf(b, "\toption domain-name %q;\n", s.Domain)
	}
	if len(s.Search) > 0 {
		fmt.Fprintf(b, "\toption domain-search %s;\n", quoted(s.Search))
	}
	if len(s.NTPServers) > 0 {
		fmt.Fprintf(b, "\toption ntp-servers %s;\n", addrs(s.NTPServers))
	}
	if s.Lease != 0 {
		fmt.Fprintf(b, "\tdefault-lease-time %d;\n", s.Lease)
	}
	if s.MaxLease != 0 {
		fmt.Fprintf(b, "\tmax-lease-time %d;\n", s.MaxLease)
	}
	for _, r := range s.Ranges {
		fmt.Fprintf(b, "\trange %s %s;\n", r.Low, r.High)
	}
	for _, h := range s.Hosts {
		fmt.Fprintf(b, "\n\thost %s {\n", h.Name)
		fmt.Fprintf(b, "\t\thardware ethernet %s;\n", h.MAC)
		fmt.Fprintf(b, "\t\tfixed-address %s;\n", addrs(h.Addrs))
		fmt.Fprintf(b, "\t\toption host-name %q;\n", h.HostName)
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
}
